spring:
  datasource:
    url: jdbc:h2:mem:app-db:inditexdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: "classpath:db/migration"
